### ISSUE TITLE
Paralel

### ISSUE THREAD

**Issue by qianweihao** [daquinterop/DSSATTools_notebooks#2]
Hello, I just used your parallel simulation example and I didn't make any changes, but I have some problems as follows:
[C:\Users\15945\AppData\Local\Temp\dssatfcsubumi](file:///C:/Users/15945/AppData/Local/Temp/dssatfcsubumi) created.
[C:\Users\15945\AppData\Local\Temp\dssatuzojhkao](file:///C:/Users/15945/AppData/Local/Temp/dssatuzojhkao) created.
[C:\Users\15945\AppData\Local\Temp\dssatehtvdhfx](file:///C:/Users/15945/AppData/Local/Temp/dssatehtvdhfx) created.
[C:\Users\15945\AppData\Local\Temp\dssatiwqzwelu](file:///C:/Users/15945/AppData/Local/Temp/dssatiwqzwelu) created.
[c:\Users\15945\AppData\Local\Programs\Python\Python311\Lib\site-packages\DSSATTools\weather.py:215](file:///C:/Users/15945/AppData/Local/Programs/Python/Python311/Lib/site-packages/DSSATTools/weather.py:215): FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = self.data.applymap(lambda x: f"{x:5.1f}")
Exception in thread Thread-5 (run_dssat):
Traceback (most recent call last):
  File "c:\Users\15945\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\15945\AppData\Roaming\Python\Python311\site-packages\ipykernel\ipkernel.py", line 761, in run_closure
Exception in thread Thread-8 (run_dssat):
Traceback (most recent call last):
  File "c:\Users\15945\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    _threading_Thread_run(self)
  File "c:\Users\15945\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self.run()
  File "C:\Users\15945\AppData\Roaming\Python\Python311\site-packages\ipykernel\ipkernel.py", line 761, in run_closure
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-6-261ceaf75e62>", line 2, in run_dssat
  File "c:\Users\15945\AppData\Local\Programs\Python\Python311\Lib\site-packages\DSSATTools\run.py", line 256, in run
    _threading_Thread_run(self)
  File "c:\Users\15945\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    assert excinfo.returncode == 0, 'DSSAT execution Failed, check '\
           ^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: DSSAT execution Failed, check [C:\Users\15945\AppData\Local\Temp\dssatfcsubumi\ERROR.OUT](file:///C:/Users/15945/AppData/Local/Temp/dssatfcsubumi/ERROR.OUT) file for a detailed report
Exception in thread Thread-7 (run_dssat):
Traceback (most recent call last):
  File "c:\Users\15945\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
...
           ^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: DSSAT execution Failed, check [C:\Users\15945\AppData\Local\Temp\dssatehtvdhfx\ERROR.OUT](file:///C:/Users/15945/AppData/Local/Temp/dssatehtvdhfx/ERROR.OUT) file for a detailed report
[c:\Users\15945\AppData\Local\Programs\Python\Python311\Lib\site-packages\DSSATTools\run.py:313](file:///C:/Users/15945/AppData/Local/Programs/Python/Python311/Lib/site-packages/DSSATTools/run.py:313): UserWarning: No output has been saved
  warnings.warn("No output has been saved")
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?089d5352-909e-48a8-9108-fc705b90a203) or open in a [text editor](command:workbench.action.openLargeOutput?089d5352-909e-48a8-9108-fc705b90a203). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

 Error in date of harvest input.  Correct input file.                            
File: WSTA0801.SGX   Line:    53   Error key: IPHAR 
Additional information may be available in WARNING.OUT file.
 
 Please press < ENTER > key to continue 

 Error in date of harvest input.  Correct input file.                            
File: WSTA0801.SGX   Line:    53   Error key: IPHAR 
Additional information may be available in WARNING.OUT file.
 
 Please press < ENTER > key to continue 

 Error in date of harvest input.  Correct input file.                            
File: WSTA0801.SGX   Line:    53   Error key: IPHAR 
Additional information may be available in WARNING.OUT file.
 
 Please press < ENTER > key to continue 

 Error in date of harvest input.  Correct input file.                            
File: WSTA0801.SGX   Line:    53   Error key: IPHAR 
Additional information may be available in WARNING.OUT file.
 
 Please press < ENTER > key to continue

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File [d:\edge\code-2-6\code-2-6\rice-irrigation\DSSATthread.py:23](file:///D:/edge/code-2-6/code-2-6/rice-irrigation/DSSATthread.py:23)
     [21](file:///D:/edge/code-2-6/code-2-6/rice-irrigation/DSSATthread.py:21) for p in processes: p.join()
     [22](file:///D:/edge/code-2-6/code-2-6/rice-irrigation/DSSATthread.py:22) for thread, cul in cultivar_maping.items():
---> [23](file:///D:/edge/code-2-6/code-2-6/rice-irrigation/DSSATthread.py:23)     output[cul] = dssat_envs[thread].output['PlantGro']
     [24](file:///D:/edge/code-2-6/code-2-6/rice-irrigation/DSSATthread.py:24) current_thread = 0
     [25](file:///D:/edge/code-2-6/code-2-6/rice-irrigation/DSSATthread.py:25) processes = []

TypeError: 'NoneType' object is not subscriptable

**Comment by daquinterop** [comment]
Hello. If you're using Windows try to run it on a Linux environment. I recommend WSL for Windows.

**Comment by hunterdanielsmith** [comment]
I have this error as well. Also example 4 is not working, ERROR.OUT wants a harvest date (IPHAR) defined.

I'm on windows.

**Comment by daquinterop** [comment]
Hi @hunterdanielsmith, I haven't had the time to solve those issues when the library is used in Windows. I recommend you in the meantime to use a Linux environment, WSL in windows is great for that.
